import { Transaction, Account } from './types';

export const mockAccount: Account = {
  balance: 12847.50,
  accountNumber: 'FI21 1234 5678 9012 34',
  currency: 'EUR',
};

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    title: 'eBike Rental - Day Pass',
    amount: -15.90,
    date: '2025-11-05T14:30:00Z',
    category: 'Transport',
    status: 'completed',
    recipient: 'Helsinki eBike Service',
    type: 'debit',
  },
  {
    id: '2',
    title: 'Salary',
    amount: 3500.00,
    date: '2025-11-01T09:00:00Z',
    category: 'Income',
    status: 'completed',
    recipient: 'Employer Ltd',
    type: 'credit',
  },
  {
    id: '3',
    title: 'eBike Monthly Subscription',
    amount: -49.90,
    date: '2025-10-28T12:15:00Z',
    category: 'Transport',
    status: 'completed',
    recipient: 'Helsinki eBike Service',
    type: 'debit',
  },
  {
    id: '4',
    title: 'Grocery Store',
    amount: -87.35,
    date: '2025-10-27T16:45:00Z',
    category: 'Shopping',
    status: 'completed',
    recipient: 'K-Market',
    type: 'debit',
  },
  {
    id: '5',
    title: 'Restaurant',
    amount: -42.50,
    date: '2025-10-26T19:30:00Z',
    category: 'Food',
    status: 'completed',
    recipient: 'Ravintola Nokka',
    type: 'debit',
  },
  {
    id: '6',
    title: 'Online Shopping',
    amount: -129.00,
    date: '2025-10-25T11:20:00Z',
    category: 'Shopping',
    status: 'completed',
    recipient: 'Amazon',
    type: 'debit',
  },
  {
    id: '7',
    title: 'Gym Membership',
    amount: -35.00,
    date: '2025-10-24T08:00:00Z',
    category: 'Health',
    status: 'completed',
    recipient: 'FitnessPark',
    type: 'debit',
  },
  {
    id: '8',
    title: 'Freelance Project',
    amount: 850.00,
    date: '2025-10-23T15:30:00Z',
    category: 'Income',
    status: 'completed',
    recipient: 'Client AB',
    type: 'credit',
  },
  {
    id: '9',
    title: 'Coffee Shop',
    amount: -6.50,
    date: '2025-10-22T10:15:00Z',
    category: 'Food',
    status: 'completed',
    recipient: 'Kahvila',
    type: 'debit',
  },
  {
    id: '10',
    title: 'Phone Bill',
    amount: -29.90,
    date: '2025-10-21T07:30:00Z',
    category: 'Bills',
    status: 'completed',
    recipient: 'Telia',
    type: 'debit',
  },
];
